[anchor]
git = "https://github.com/asterinas/asterinas.git"
tag = "v0.16.0"

[[modules]]
name = "rcu"
path = "/home/xxx/asterinas-fv/tools/alignment-checker/modules/rcu.toml"
source = "/home/xxx/asterinas-fv/ostd/src/sync/rcu"

[[modules]]
name = "mm"
path = "/home/xxx/asterinas-fv/tools/alignment-checker/modules/mm.toml"
source = "/home/xxx/asterinas-fv/ostd/src/mm"
