name: Format DV Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt

      - name: Check for formatting changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Code is not properly formatted. Run 'make fmt'."
            git diff
            exit 1
          fi